### ISSUE TITLE
maor php-ness

### ISSUE THREAD

**Issue by mbrevda** [danielmewes/php-rql#101]
php-rql is currently written to mimic RethinkDB's javascript api. While this reduces the amount of documentation needed, it greatly ups the learning for php dev's, used to working in a more php centric way. Here are a couple of ideas and suggestiong that would be great to discuss:

- [x] **Proper object oriented-ness:** Using a myriad of global(ish) functions and having to pass them low level data all the time creates a high maintenance price on developers. For example: having to pass a db connection or name to every `r\table()` query requires having this information in some sort of global state. **issue largely mitigated with DI**
- [x] **DI-able:** having a containing object as the starting point for all queries will allow for that object to be configured/instantiated/injected by a dependency injection system. This will, again, lower the overhead of global state that needs to be kept in order to run a query.
 **with #107, a Connection and a Db can be injected and used without any other dependencies**
- [x] **Lazy connection:** once we are more di-able, it would make more sense to not run [`$this->connect();`](https://github.com/danielmewes/php-rql/blob/master/src/rdb/connection.php#L25) until a connection is actually needed. This would cut down the overhead of server hits where the db isn't actually used (say, where an in-memory cache already provided the data required) **#107**
- [x] **PSR Compatibility:** Things like PSR-1, PSR-2, and PSR-4 make it easier to jump in to the code and understand what going on. It also allows for:
- [x] **Lazy includes:** There is no need to load all the code at once. Composer's ubiquitous autoloader can intelligently load just those classes that are needed, as they are needed
- [x] **Saner API:** Again recognizing the original goal of uniformity with the js docs, the api seems a bit backwards. For example, which of the following is more [self-documenting](https://en.wikipedia.org/wiki/Self-documenting)?
  * `$result = r\table("tablePhpTest")->insert($document)->run($conn);`
  * vs
  * `$result = $rdb->table("tablePhpTest")->insert($document)->run();`
  * or perhaps: `$result = $rdb->insert($document)->inTo("tablePhpTest")->run();`

 or
  * `$result = r\table("tablePhpTest")->map(function($x) {return $x('someKey');})->run($conn)`
  * vs
  * `$result = $rdb->table("tablePhpTest")->map(function($x) {return $x('someKey');})->run()`
 **Note: marking this as "done" in the sense that it is being handeled upstream: https://github.com/rethinkdb/rethinkdb/issues/3130**
- [x] **Separate query and connection:** I also wonder if `run()` at the end of every query is really necessary. It seems that the "rql" way of doing things is to keep the query and connection parts separate. It might be better to have a Connection object, which gets passed a Query. I.e.: 
  * `$rdb->run((new Table('foo'))->insert($document));`
  **this is currently implemented by default**
- [x] **Proper unit testing**: a standard framework, like phpunit, would make it easier to test, and also, refactor **done in #105**

None of the above should be seen as criticism to the current project, but rather some suggestions on how the learning curve can be lowered, hopefully leading to greater adoption.

**Comment by smazurov** [comment]
I agree with some points, mainly unit tests, PSR, lazy connections/includes.

I don't agree that we need "proper" OO, DI, "Saner API". There is a lot to be said for having mostly similar looking API as the javascript client, as well as very easy conversion from Data Explorer to PHP code. 

Docblocks and typehints where possible would greatly help, but changing things for the sake of looking more like traditional PHP should not be a goal of this library. Its actually pretty trivially easy to write a wrapper that handles your use-case of managing connections, etc. 

As an example, I was able to write:

```js
r.db('gh_packages').table('packages').filter(function(pkg) {
  return pkg('metadata')('assets').count().gt(0)
})
```

and translate it very easily to php:

```php
$this->getTable()->filter(function ($package) {
  $metadata = $package('metadata');
  return $metadata('assets')->count()->gt(0);
})->run($this->manager->connection());
```

That said, some of the features (such as connection pools) could be implemented in a way that isn't destructive to api compatibility, so you could, after properly initializing, simply call `->run()`

**Comment by mbrevda** [comment]
@smazurov having gone through the code a bit, I would agree with most of what you said. I still don't think that having to prefix every function or having to pass around a connection all over is a good idea. For starters I would recommend the following:

 1. Make $conn optional (i.e. `$rdb->table...->run()`)
 2. Make table commands chainable instead of being methods. (i.e. `$rdb->table('foo')->create()->run()`)
 3. Have a query factory. This would allow for just dependencies to be injected in to a class, providing (I think?) everything necessary to build and execute a query: The db object, and the query builder that can add other things (like map())

BTW, phpunit and PSR are done, just waiting for review/merge

**Comment by danielmewes** [comment]
Many of the points you mention have actually been discussed / are being discussed upstream for ReQL in general.
I'd like to stay very close to the API that the official ReQL drivers use, for the mentioned reasons and because it makes PHP-RQL much easier to maintain over time.

See the following upstream issues:

> Make $conn optional (i.e. $rdb->table...->run())

https://github.com/rethinkdb/rethinkdb/issues/3602 (including the general idea of having an instance of `r` rather than a global object / namespace.

> Make table commands chainable instead of being methods. (i.e. $rdb->table('foo')->create()->run())

I think this one should definitely be a server-side feature, not something the driver should do. See https://github.com/rethinkdb/rethinkdb/issues/3130

I'm not entirely sure what you mean by the "query factory". Isn't any partial query in PHP-RQL basically a query factory, with the one exception of not including the connection?

**Comment by danielmewes** [comment]
Note that there's no need currently to pass a table or DB name to every place where you use a table. Just do something like
```php
$table = r\db("db")->table("table");
```
and you can use the `$table` variable to build all sorts of other queries without them needing to know anything about the db or table name. You can obviously stick this into some structure together with a connection object as well.


Another note: Some sort of `run()` at the end of a query is necessary, because the driver has no way to determine when the query is complete and should be sent over to the server. This is a consequence of the fact that ReQL allows chaining operations behind each other. So any prefix of a complete query is by itself a complete query.

**Comment by danielmewes** [comment]
Sorry I'm being a bit dismissive about some of the deeper changes to the driver. This is partially because in the end I have to maintain it, and moving more logic and complications into the driver would make it harder for me to keep up with upstream developments.

That being said, I like the PSR changes, and I think moving to phpunit is also a good idea. I haven't been following developments around PHP too closely for the past years, so I appreciate getting contributions from someone who obviously understands a lot better what's expected from a modern PHP library! :-)

**Comment by mbrevda** [comment]
I would be concerned if you *weren't* at least slightly sceptical!

While you're correct that `$table` can be passed around all over the place, it sounds like you're advocating using a global object. Preferable would be to use dependency injection to **inject the table object where it's needed**, or even better, a db object, which can be easily chained to reach `table()`. To do that, I'm proposing the following:

 1. Allow lazy-connects to minimize the initial creation cost of `Connection` (herein: `$rdb`). No need to open a socket if `$rdb` doesn't end up being used.
 2. `$rdb` can be injected wherever it's needed, and can be chained as it currently is. I.e.: `$rdb->table('foo)->/* do something */->run();`
 3. `run()` should accept an OPTIONAL `$conn` object. If none is passed, use the default
 4. For all the other query objects (i.e. `exper`, `js`, `row`, date/month/dow/etc), offer a factory that can create the object, with the default connection already injected. Here is a rough gist showing how the code would work (mostly pseudo code). This would allow for just **two** object to be injected in any given class, and still offer full, properly namespaced, access to all parts of the driver:
  1. `$rdb`
  2. The query factory

**Comment by smazurov** [comment]
regarding point 2, i think whatever DI your framework uses is a better solution to adding something to the rql lib.

**Comment by mbrevda** [comment]
@smazurov "s/better solution/only solution". Obviously, the DI of choice would do the injection - I don't propose adding anything of the sort to the driver - I was just illustrating *how* it would be possible.

**Comment by mbrevda** [comment]
On the topic of `run()` not requiring a `$conn` option: I'm reconsidering my position, in favor of keeping the connection and the query fully abstracted. Instead, `$rdb->run((new Table('foo'))->insert($document));` can achieve something similar.
