### ISSUE TITLE
Select all documents in a table

### ISSUE THREAD

**Issue by ryanaverill** [danielmewes/php-rql#97]
I'm running the last version of php-rql but when I run something like this:  

$data = r\table($collection)->run($conn);
var_dump($data); 

I'm expecting something like rethinkdb returns:

{
"firstName":  "first" ,
"id":  "5d5ccdc7-3e6d-4c1d-a564-d2fa87d46b51" ,
"lastName":  "last"
}

But instead I get something like this. I can clean this up myself but is this expected, any chance there is an output option to clean up this extra verbose info? Hopefully that makes sense

object(r\Cursor)#31 (9) {
  ["token":"r\Cursor":private]=>
  int(263484269)
  ["connection":"r\Cursor":private]=>
  object(r\Connection)#26 (7) {
    ["socket":"r\Connection":private]=>
    resource(5) of type (stream)
    ["host":"r\Connection":private]=>
    string(14) "192.168.33.149"
    ["port":"r\Connection":private]=>
    int(28015)
    ["defaultDb":"r\Connection":private]=>
    object(r\Db)#21 (3) {
      ["positionalArgs":"r\Query":private]=>
      array(1) {
        [0]=>
        object(r\StringDatum)#22 (4) {
          ["value":"r\Datum":private]=>
          string(4) "test"

**Comment by danielmewes** [comment]
@ryanaverill the returned object is a cursor. Since a table can be much too large to fit into memory on the client, RethinkDB returns it in chunks rather than all at once.
A cursor can be iterated over, and more chunks are requested from the server as needed while doing that.

There are three options to get all data:
1. Iterating over the cursor and handling the data one document at a time:
```php
$cursor = r\table($collection)->run($conn);
foreach ($doc in $cursor) {
    var_dump($doc);
}
```
2. Convert the cursor into an array on the client side (make sure the table is small, or you might run out of memory):
```php
$cursor = r\table($collection)->run($conn);
$allData = $cursor->toArray();
var_dump($allData); // $allData is now an array of all the documents
```
This uses the `toArray` method http://danielmewes.dnsalias.net/~daniel/php-rql-api/#Cursors
3. Convert the table into an array on the server side (this is limited to 100,000 elements by default, and can use large amounts of memory both on the server and the client if the table is large):
```php
$allData = r\table($collection)->coerceTo("ARRAY")->run($conn);
var_dump($allData);
```
This uses the `coerceTo` ReQL command http://danielmewes.dnsalias.net/~daniel/php-rql-api/#Control+structures

**Comment by ryanaverill** [comment]
Awesome, thank you so much!
